import { defineEntity } from '../platform-api';

export const CustomerEntity = defineEntity({
  id:          'customer',
  displayName: 'Customer',
  pluralName:  'Customers',
  description: 'A business or individual customer record',
  icon:        'people',
  permissions: ['customers:read', 'customers:write'],
  fields: [
    { key: 'firstName',    type: 'text',     label: 'First Name',    required: true },
    { key: 'lastName',     type: 'text',     label: 'Last Name',     required: true },
    { key: 'displayName',  type: 'text',     label: 'Display Name' },
    { key: 'customerType', type: 'select',   label: 'Customer Type', required: true },
    { key: 'industry',     type: 'select',   label: 'Industry' },
    { key: 'email',        type: 'text',     label: 'Email Address',
      validators: [{ type: 'email' }] },
    { key: 'phone',        type: 'text',     label: 'Phone Number',
      validators: [{ type: 'phone' }] },
    { key: 'website',      type: 'text',     label: 'Website' },
    { key: 'vatNumber',    type: 'text',     label: 'VAT Number' },
    { key: 'street',       type: 'text',     label: 'Street' },
    { key: 'city',         type: 'text',     label: 'City' },
    { key: 'state',        type: 'text',     label: 'State / Province' },
    { key: 'postcode',     type: 'text',     label: 'Postcode' },
    { key: 'country',      type: 'select',   label: 'Country' },
    { key: 'sameAsBilling', type: 'checkbox', label: 'Same as billing address' },
    { key: 'currency',     type: 'select',   label: 'Currency' },
    { key: 'language',     type: 'select',   label: 'Language' },
    { key: 'isActive',     type: 'switch',   label: 'Active' },
    { key: 'isTaxExempt',  type: 'switch',   label: 'Tax Exempt' },
    { key: 'internalNotes', type: 'textarea', label: 'Internal Notes' },
    { key: 'tags',         type: 'chip',     label: 'Tags' },
    { key: 'accountManager', type: 'select', label: 'Account Manager' },
  ],
  metadata: {
    apiPath:     '/api/customers',
    primaryKey:  'id',
    searchable:  true,
    auditable:   true,
  },
});
